ARG BASE_IMAGE=adamrehn/ue4-minimal:5.2.0-opengl-ubuntu22.04
FROM $BASE_IMAGE

USER root
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y --no-install-recommends \
	rsync \
    sudo \
    wget \
    x11-xserver-utils

RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers && \
    adduser ue4 sudo 

USER ue4
RUN cd /home/ue4 && \
	git clone --progress -b jammy-22.04 https://github.com/Leedk3/AirSim.git && \
	cd AirSim && \
	./setup.sh && \
	./build.sh

WORKDIR /home/ue4
